# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg Gibeling
description: Hardware & software architect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Charcoal settings
author_name: Greg Gibeling
author_url: https://github.com/gdgib/
github_username: gdgib
linkedin_username: greg-gibeling-91924676

# Blog settings
show_excerpts: true
excerpt_separator: "<!-- more -->"

# Theme settings
#  Uncomment these for local testing, comment them out when publishing
#repository: g2forge/g2forge.github.io
#theme: jekyll-theme-charcoal
#  Uncomment these for publishing, comment them out for testing
remote_theme: g2forge/charcoal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
