# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg Gibeling
description: Hardware & software architect. Coding is an art and a hobby.
image: /images/ProfileMedium.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Charcoal settings
author_name: Greg Gibeling
author_url: https://www.gdgib.com/
email: gdgib@outlook.com
github_username: gdgib
linkedin_username: greg-gibeling-91924676
bare: false
toc: true
credits: true

# Blog settings
show_excerpts: true
excerpt_separator: "<!-- more -->"

# Theme settings
#  Uncomment these for local testing, comment them out when publishing
#repository: gdgib/gdgib.github.io
#theme: jekyll-theme-charcoal
#  Uncomment these for publishing, comment them out for testing
remote_theme: g2forge/charcoal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
  jobs:
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: jobs
  values:
    layout: job
    bare: true
